const fatosHistoricos = [
    {"Ano": "1920", "Fato": "As mulheres ganham o direito ao voto nos EUA"},
    {"Ano": "1921", "Fato": "O partido comunista chinÃªs Ã© fundado"},
    {"Ano": "1922", "Fato": "O impÃ©rio britÃ¢nico diminui"},
    {"Ano": "1923", "Fato": "Ocorreu o grande terremoto na regiÃ£o de Kanto, no JapÃ£o"},
    {"Ano": "1924", "Fato": "Joseph Stalin assume o lugar de Vladmir Lenin"},
    {"Ano": "1925", "Fato": "O estado americano processa John Thomas Scopes por ensinar evolucionismo em uma escola do Tennessee."},
    {"Ano": "1926", "Fato": "Os EUA iniciam o seu sistema de autoestradas numeradas"},
    {"Ano": "1927", "Fato": "Charles Lindbergh se torna a primeira pessoa a pilotar um aviÃ£o sobre o oceano atlÃ¢ntico sem escalas."},
    {"Ano": "1928", "Fato": "Amelia Earhart se torna a primeira mulher a cruzar o atlÃ¢ntico pilotando um aviÃ£o."},
    {"Ano": "1929", "Fato": "Ocorre a quebra da bolsa de valores de Nova York."},
    {"Ano": "1930", "Fato": "Ho Chi Minh funda o partido comunista do VietnÃ£"},
    {"Ano": "1931", "Fato": "A construÃ§Ã£o do Epire State Building Ã© concluÃ­da."},
    {"Ano": "1932", "Fato": "Hitler renÃºcia a sua cidadania austrÃ­aca e se torna alemÃ£o"},
    {"Ano": "1933", "Fato": "Franklin  D. Roosvelt Ã© eleito presidente dos Estados Unidos"},
    {"Ano": "1934", "Fato": "Hitler se consolida no poder."},
    {"Ano": "1935", "Fato": "O presidente Franklin Roosvelt anuncia o New Deal, criando o primeiro sistema de seguro social para aposentados do paÃ­s."},
    {"Ano": "1936", "Fato": "O corredor Afro-Americano Jesse Owens ganha 4 medalhas de ouro nas olimpÃ­adas de Berlim durante o nazismo de Hitler."},
    {"Ano": "1937", "Fato": "Trabalhadores da General Motors protestam por 44 dias ocupando a fÃ¡brica da GM e conseguem uma aumento de 5% no pagamento."},
    {"Ano": "1938", "Fato": "O movimento anti-semita se inicia na Alemanha durante o Nazismo de Hitler."},
    {"Ano": "1939", "Fato": "Tem inÃ­cio a segunda guerra mundial"},
    {"Ano": "1940", "Fato": "O McDonalds Ã© fundado."},
    {"Ano": "1941", "Fato": "Tropas japonesas atacam a base de Pearl Harbor"},
    {"Ano": "1942", "Fato": "Tropas americanas chegam a Irlanda do Norte para lutar na guerra da Europa."},
    {"Ano": "1943", "Fato": "O quÃ­mico suÃ­Ã§o Albert Hoffman descobre acidentalmente o LSD"},
    {"Ano": "1944", "Fato": "Ocorre a invasÃ£o da Normandia pelas forÃ§as aliadas para tirar as tropas nazistas da FranÃ§a"},
    {"Ano": "1945", "Fato": "A segunda guerra mundial termina com ataques atÃ´micos a Hiroshima e Nagazaki, que causaram a rendiÃ§Ã£o do JapÃ£o."},
    {"Ano": "1946", "Fato": "Tem inÃ­cio a geraÃ§Ã£o Baby Boom, sÃ³ em 1946 foram mais de 3.4 milhÃµes de crianÃ§as nascidas sÃ³ nos EUA."},
    {"Ano": "1947", "Fato": "A Ãndia consegue sua independÃªncia do impÃ©rio britÃ¢nico, mas acaba divida e se torna duas naÃ§Ãµes, a Ãndia, para os HindÃºs e o PaquistÃ£o, para os muÃ§ulmanos."},
    {"Ano": "1948", "Fato": "Acontece o nascimento do estado de Israel"},
    {"Ano": "1949", "Fato": "Ã‰ fundada a OrganizaÃ§Ã£o do Tratado do AtlÃ¢ntico Norte, a OTAN, para combater a ameaÃ§a SoviÃ©tica."},
    {"Ano": "1950", "Fato": "Tem inÃ­cio a Guerra das CorÃ©ias, quando a CorÃ©ia do Norte invade a CorÃ©ia do Sul, despertando a resposta imediata dos Estados Unidos. A guerra dura trÃªs anos."},
    {"Ano": "1951", "Fato": "Julius e Ethel Rosenberg sÃ£o condenados a morte nos EUA por espionagem, apÃ³s terem vazado informaÃ§Ãµes sobre bombas atÃ´micas para a UniÃ£o SoviÃ©tica."},
    {"Ano": "1952", "Fato": "Os Estados Unidos detonam a primeira bomba de hidrogÃªnio."},
    {"Ano": "1953", "Fato": "Os cientistas James Watson e Francis Crick, da Universidade de Cambridge, sÃ£o os primeiros a explicar o funcionamento do DNA na replicaÃ§Ã£o dos genes e a sua transmissÃ£o para as futuras geraÃ§Ãµes."},
    {"Ano": "1954", "Fato": "Linda Brown vence a disputa contra o conselho de educaÃ§Ã£o e a suprema corte americana julga inconstitucional a segregaÃ§Ã£o racial em escolas."},
    {"Ano": "1955", "Fato": "Rosa Parks faz histÃ³ria ao se recursas a se levantar e dar lugar a um branco no Ã´nibus. Sua prisÃ£o leva a um boicote a empresa e a ascenÃ§Ã£o do Pastor Martin Luther King Jr."},
    {"Ano": "1956", "Fato": "Protestos na Hungria por democracia acaba na morte de milhares apÃ³s invasÃ£o do Exercito Vermelho da Comunista UniÃ£o SoviÃ©tica."},
    {"Ano": "1957", "Fato": "O president Dwight Eisenhower ordena as tropas federais que proteja 9 alunos afro-americanos que comeÃ§aram a estudar no colÃ©gio Little Rock para alunos brancos, essa foi a primeira aÃ§Ã£o do governo federal contra a segregaÃ§Ã£o racial no paÃ­s."},
    {"Ano": "1958", "Fato": "Os Estados Unidos lanÃ§am seu primeiro satÃ©lite, o Explorer 1."},
    {"Ano": "1959", "Fato": "Fidel Castro invade cuba e se consolida no poder, dando inÃ­cio a ditadura comunista."},
    {"Ano": "1960", "Fato": "O restaurante Woolworth se recusa a atender 4 jovens afro-americanos, desencadeando uma enorme onda de protestos que durou 6 meses e resultou no fim da segregaÃ§Ã£o nos restaurantes."},
    {"Ano": "1961", "Fato": "Ocorre a construÃ§Ã£o do muro de Berlin"},
    {"Ano": "1962", "Fato": "A UniÃ£o SoviÃ©tica testa misseis em Cuba, a 145km ao sul de Miami, dando inÃ­cio a resposta dos EUA sob o comando de John F Kennedy. A resposta de Kennedy faz a UniÃ£o SoviÃ©tica remover os mÃ­sseis de Cuba."},
    {"Ano": "1963", "Fato": "John F. Kennedy Ã© assassinado."},
    {"Ano": "1964", "Fato": "O presidente Lyndon Johnson dÃ¡ inicio a sua 'Guerra Ã  Pobreza', destacando a necessidade de reduzir a probreza, acabar acabar com a segregaÃ§Ã£o racial e cuidar da saÃºde dos idosos do paÃ­s. Lyndon Johnson criou ainda o ato dos direitos civis no mesmo ano."},
    {"Ano": "1965", "Fato": "O assassinato de Jimmy Lee Jackson pelas tropas do Alabama desencadeia uma passeata em protesto. O evento ficou conhecido como Domingo Sangrento."},
    {"Ano": "1966", "Fato": "Mao Zedong inicia o extermÃ­nio de seus rivais polÃ­ticos. O lÃ­der comunista enviou diversos opositores para campos de reeducaÃ§Ã£o e trabalho forÃ§ado, e assassinou diversos outros que se opuseram ao seu governo."},
    {"Ano": "1967", "Fato": "Acontece a guerra dos seis dias. SÃ­ria, JordÃ¢nia, Iraque e Egito atacam Israel, a guerra termina em 6 dias, com um cessar fogo apÃ³s Israel ocupar areas importantes dos 4 paÃ­ses."},
    {"Ano": "1968", "Fato": "Martin Luther King Ã© assassinado."},
    {"Ano": "1969", "Fato": "Neil Armstrong, Buzz Aldrin e Michael Collins sÃ£o as primeiras pessoas a pisarem na lua"},
    {"Ano": "1970", "Fato": "A guerra na Ã¡sia aumenta e desperta protestos anti-guerra nos Estados Unidos dado o involvimento do paÃ­s no continente."},
    {"Ano": "1971", "Fato": "New York Times publica documentos sobre o envolvimento do governo amerino na guerra do VietnÃ£"},
    {"Ano": "1972", "Fato": "O Presidente Anti-Comunista Richard Nixon faz sua primeira viagem oficial a China, com o objetivo de melhorar a relaÃ§Ã£o entre os dois paÃ­ses."},
    {"Ano": "1973", "Fato": "A suprema corte define que os estados podem impedir o aborto a partir do terceiro trimestre de gestaÃ§Ã£o, exceto quando a gestaÃ§Ã£o oferece risco a vida da mulher."},
    {"Ano": "1974", "Fato": "O presidente Richard Nixon Renuncia durante o processo de impeachment causado pelo escandalo de Watergate."},
    {"Ano": "1975", "Fato": "Dois anos depois as Ãºltimas tropas americanas deixarem o VietnÃ£, as tropas comunistas capturam Saigon."},
    {"Ano": "1976", "Fato": "Dois jatos super-sÃ´nicos Concorde levatam voo simultÃ¢neamente. Um partindo de Londres para o Barein, e outro de Paris, para o Rio de Janeiro."},
    {"Ano": "1977", "Fato": "Os primeiros computadores pessoais modernos comeÃ§am a surgir"},
    {"Ano": "1978", "Fato": "Mais de 900 pessoas morrem em um suÃ­cidio em massa promovido por um culto em Jonestown, promovido por Jim Jones."},
    {"Ano": "1979", "Fato": "O IrÃ£ se torna uma repÃºblica islÃ¢mica"},
    {"Ano": "1980", "Fato": "Ronald Reagan Ã© eleito presidente dos Estados Unidos."},
    {"Ano": "1981", "Fato": "Surge a AIDS nos Estados Unidos"},
    {"Ano": "1982", "Fato": "Governo Mexicano diz a reserva federal dos Estados Unidos que o paÃ­s nÃ£o consegue pagar o emprÃ©stimo de 80 bilhÃµes de dÃ³lares."},
    {"Ano": "1983", "Fato": "Acontece o nascimento da Internet"},
    {"Ano": "1984", "Fato": "Desastre quÃ­mico em Bophal, India, afeta mais de 600 mil pessoas, matando mais de 15 mil dessas. "},
    {"Ano": "1985", "Fato": "Ronald Reagan se encontra com o SecretÃ¡rio Geral da UniÃ£o SoviÃ©tica, Mikhail Gorbachev"},
    {"Ano": "1986", "Fato": "A nave Challenger exploduiu 73 segundos apÃ³s decolar do Cabo Canaveral, causando a morte de 7 astronautas."},
    {"Ano": "1987", "Fato": "A bolsa Dow Jones tem uma queda de 508 pontos, uma situaÃ§Ã£o pior que a da quebra de 1929."},
    {"Ano": "1988", "Fato": "O Tenente Coronel Oliver North e o Vice Almirante John Pointdexter sÃ£o indiciados por conspiraÃ§Ã£o apÃ³s venderem armas para o IrÃ£ a fim de facilitar a soltura de refÃ©ns americanos."},
    {"Ano": "1989", "Fato": "Acontece a queda do muro de Berlin."},
    {"Ano": "1990", "Fato": "Com o enfraquecimento da UniÃ£o SoviÃ©tica e do comunismo, a PolÃ´nia dissolve o partido comunista e elege seu primeiro presidente, Lech Walesa."},
    {"Ano": "1991", "Fato": "Os Estados Unidos vÃ£o para a guerra do oriente mÃ©dio apÃ³s Sadam Hussain invadir o Kuait."},
    {"Ano": "1992", "Fato": "A guerra fria entre RÃºssia e os EUA termina semanas apÃ³s o fim da UniÃ£o SoviÃ©tica."},
    {"Ano": "1993", "Fato": "Ã‰ criada a UniÃ£o EuropÃ©ia."},
    {"Ano": "1994", "Fato": "O site Amazon.com Ã© lanÃ§ado"},
    {"Ano": "1995", "Fato": "Ataque terrorista acontece em Olklahoma com a explosÃ£o de um caminhÃ£o-bomba."},
    {"Ano": "1996", "Fato": "A ovelha Dolly Ã© Clonada com sucesso"},
    {"Ano": "1997", "Fato": "A IBM Deep Blue se tornou a primeira mÃ¡quina a derrotar um campeÃ£o do Xadrez, derrotando Garry Kasparov duas vezes e empatando com ele trÃªs vezes em 6 partidas."},
    {"Ano": "1998", "Fato": "Ã‰ lanÃ§ado o buscador Google"},
    {"Ano": "1999", "Fato": "A OTAN inicia sua primeira campanha militar"},
    {"Ano": "2000", "Fato": "A estaÃ§Ã£o espacial internacional Ã© inaugurada."},
    {"Ano": "2001", "Fato": "As torres gÃªmeas do World Trade Center sÃ£o derrubadas em um ataque terrorista"},
    {"Ano": "2002", "Fato": "George W. Bush cria o departamento de seguranÃ§a nacional."},
    {"Ano": "2003", "Fato": "Os Estados Unidos inciam os ataques ao Iraque"},
    {"Ano": "2004", "Fato": "O Facebook Ã© fundado"},
    {"Ano": "2005", "Fato": "o FuracÃ£o Katrina destrÃ³i New Orleans."},
    {"Ano": "2006", "Fato": "Saddam Hussein Ã© executado"},
    {"Ano": "2007", "Fato": "Apple anuncia seu primeiro smartphone, o iPhone"},
    {"Ano": "2008", "Fato": "O indicador Dow Jones despenca outra vez, dessa vez caindo 777 pontos."},
    {"Ano": "2009", "Fato": "Barack Obama Ã© eleito presidente dos Estados Unidos e se torna o primeiro presidente afro-americano do paÃ­s."},
    {"Ano": "2010", "Fato": "11 trabalhadores morrem e 17 ficam feridos em uma explosÃ£o na costa da Lousiana em uma exploraÃ§Ã£o de Ã³leo."},
    {"Ano": "2011", "Fato": "Bin Laden Ã© assassinado."},
    {"Ano": "2012", "Fato": "Cientistas do CERN descobrem uma nova partÃ­cula atravÃ©s do colisor de hadrons que eles acreditam ser o BÃ³son de Higgs, a chamada 'PartÃ­cula de Deus'."},
    {"Ano": "2013", "Fato": "Edward Snowden expÃµes segredos de estado dos Estados Unidos e de governos europeus sobre espionagem de outros paÃ­ses."},
    {"Ano": "2014", "Fato": "O Presidente Russo Vladmir Putin orquestra anexar a Crimeia Ã  RÃºssia, causando sanÃ§Ãµes dos lÃ­deres mundiais ao paÃ­s."},
    {"Ano": "2015", "Fato": "A nave New Horizon se torna o primeiro objeto criado pela humanidade a passar por PlutÃ£o e observar o planeta de perto."},
    {"Ano": "2016", "Fato": "Donald Trump Ã© eleito presidente dos Estados Unidos"},
    {"Ano": "2017", "Fato": "Em um espaÃ§o de 4 semanas, 3 furaÃ§Ãµes atingem os Estados Unidos, Harvey, Irma e Maria atingiram o Texas, Florida e  o Caribe"},
    {"Ano": "2018", "Fato": "Queimadas destroem a Carolina do Norte"},
    {"Ano": "2019", "Fato": "Protestos ocorrem em Hong Kong contra tentativa da China de tirar a autonomia do paÃ­s."},
    {"Ano": "2020", "Fato": "Tem inÃ­cio a pandemia de COVID-19"}
];

export default fatosHistoricos;